#!/bin/bash
shopt -s extglob

if [ -n "$(cd . 2>&1)" ]; then
    echo "Can't run ${BASH_SOURCE[0]} from a non-existent directory!"
    exit 1
fi

here=$(cd "${BASH_SOURCE[0]%/*}" && pwd)

ENV_FILE=${0##*/}.env

pushes=()
function push {
    pushd "$1" > /dev/null
    pushes=(${pushes[@]} ".")
}

until [ "$PWD" = "/" ]; do
    if [ -f "$ENV_FILE" ]; then
        . "$ENV_FILE"
        break
    fi
    push ..
done
for x in "${pushes[@]}"; do
    popd > /dev/null
done

exec $(which -a git | grep -v "$here/${0##*/}" | head -1) "$@"
