#!/usr/bin/env bash
[ $BASH_VERSINFO -gt 3 ] || { echo "Bash 4+ is required."; exit 1; }

set -o errexit -o pipefail -o nounset
shopt -s extglob nullglob
unset CDPATH

declare -ir ERR_GENERAL=1
declare -ir ERR_BAD_CMD_LINE=113
declare -ir ERR_PRECONDITION_VIOLATED=112
declare -ir ERR_MAX_LINK_DEPTH_EXCEEDED=111
declare -ir ERR_CMD_NOT_FOUND=110
declare -ir ERR_NON_EXISTENT_DIR=109
# Use 64-100 for other exit codes.

declare -r here=$(cd -- "${BASH_SOURCE[0]%/*}" && pwd)

display_help() {
cat <<EOF
usage: ${0##*/} [opts]

-h|--help        Display usage information.

Run lnav via an Ubuntu Docker container on MacOS (native otherwise).
Mounts \$HOME/.lnav, \$HOME, and /tmp

$(
if [[ $(uname -s) == Darwin ]]; then
    docker run --rm --interactive --tty lnav -h
else
    $(which -a lnav | grep -v "$here/${0##*/}" | head -1) -h
fi
)
EOF
}
require() {
    eval [[ \$\{${1:?require was called without arguments!}-\} ]] \
         '||' abort \$ERR_BAD_CMD_LINE \$\{2-\$1 is required!\} \$\{*:3\}
}
abort() {
    local -i err_code=${1:?abort called without err_code}
    (( err_code == ERR_BAD_CMD_LINE )) && {
        display_help; echo; echo "-- ABORTED:"
    }
    shift; (( $# > 0 )) && echo "$*" >&2
    exit $err_code
}

main() {
    local tz

    if [[ $(uname -s) = Darwin ]]; then
        if [[ $(tty) == 'not a tty' ]]; then
            exec "$here"/lnav-0.8.4-macos "$@"
        else
            local -a args
            while (( $# > 0 )); do
                case $1 in
                    -[hHiuCVarRtnq])
                        args+=("$1")
                        ;;
                    -[Idwcf])
                        args+=("$1" "$2")
                        shift
                        ;;
                    /*)
                        args+=("$1")
                        ;;
                    *)
                        args+=("$PWD/$1")
                        ;;
                esac
                shift
            done
            docker run \
                   --rm \
                   --interactive \
                   --tty \
                   -v $HOME/.lnav:/root/.lnav \
                   -v $HOME:/Users/bstiles \
                   -v /tmp:/tmp \
                   -e TERM=screen-256color \
                   lnav "${args[@]}"
        fi
    else
        exec $(which -a lnav | grep -v "$here/${0##*/}" | head -1) "$@"
    fi
}

# Handle help
[[ ${1-} == @(--help|-h) ]] && { display_help; exit 0; }
main "$@"
