#!/bin/bash
shopt -s extglob

if [ -n "$(cd . 2>&1)" ]; then
    echo "Can't run ${BASH_SOURCE[0]} from a non-existent directory!"
    exit 1
fi

SCRIPT=$(basename "$0")

until [ "$PWD" = "/" ]; do
    if [ -x "$SCRIPT" ]; then
        SCRIPT=$PWD/$SCRIPT
        break
    fi
    pushd .. > /dev/null
done
[[ -x $SCRIPT ]] || {
    echo "Couldn't find $SCRIPT executable. Are you in a project?"
    exit 1
}

dirs +1 > /dev/null 2>&1 && popd > /dev/null
exec "$SCRIPT" "$@"
