#!/bin/bash
. "$(dirname "$0")"/init.sh

LINES_TO_CHECK=2
#######################################################################################
# The template is the stuff above.  The script below checks all the
# scripts in ~/bin for compliance.

THIS_SCRIPT_NAME="$(basename "$0")"
cd "$(dirname "$0")"
for x in *[^~]; do
    file "$x" | grep -q 'script text'
    grep_exit=$?
    if [ $grep_exit -eq 1 ]; then
	echo "Ignoring non-script: $x"
	file "$x"
	echo "-------------------------------------------------------------"
	continue
    fi
    if [ $grep_exit -eq 2 ]; then
	echo "!!!!!!!!!!!!!!!!!!!!!"
	echo "grep barfed on $x"
	echo "!!!!!!!!!!!!!!!!!!!!!"
	echo "-------------------------------------------------------------"
	continue
    fi
    MASTER="$(tempfile -s "$x")"
    COPY="$(tempfile -s "$x")"
    head -n $LINES_TO_CHECK "$THIS_SCRIPT_NAME" > "$MASTER"
    head -n $LINES_TO_CHECK "$x" > "$COPY"
    diff "$MASTER" "$COPY"
    if [ $? -ne 0 ]; then
	echo "!!"
	echo "!! $x is out of date"
	echo "!!!!!!!!!!!!!!!!!!!"
	echo "-------------------------------------------------------------"
    fi
done
