#!/bin/bash
shopt -s extglob

function abort {
    if [ -n "$1" ]; then
        echo "$1"
    fi
    exit 1
}

asking_for_help=false
case "$1" in
    --help|-h)
        asking_for_help=true
        ;;
esac

here="$(cd "$(dirname "$0")";pwd)"

function display_help {
    echo "usage: $(basename "$0") [--banner] args..."
    echo "    --banner        Display a banner showing the project dir for each project"
    echo "    args...         Args to pass on to hg for each project"
    echo
    echo "Finds each Mercurial project in the current working directory and"
    echo "below and executes 'args...' in with the project root as the current"
    echo "working dir."
}

if [ $asking_for_help = true ]; then
    display_help
    exit 0
fi

## END TEMPLATE

exec "$here/do-in-projects" '( -path \*/.svn -o -path \*/.hg ) -prune -o -type d -name .hg' "$@"
