#!/bin/bash
shopt -s extglob

function abort {
    if [ -n "$1" ]; then
        echo "$1"
    fi
    exit 1
}


here="$(cd "$(dirname "$0")";pwd)"


## END TEMPLATE

exec java -cp "$here/h2-1.3.149.jar" org.h2.tools.Shell "$@"
