#!/bin/bash
. "$(dirname "$0")"/init.sh

etc_dir="$(dirname "$0")/etc"
CFGFILE="$etc_dir/hsql.conf"
. "$CFGFILE"

cd "$HSQL_HOME"

exec "$JAVA_EXECUTABLE" $CLIENT_JVMARGS -Xbootclasspath/p:/Users/bstiles/bin/h2-1.3.149.jar -jar "${HSQLDB_JAR_PATH}" --rcFile "$AUTH_FILE" "$@"
#exec "$JAVA_EXECUTABLE" $CLIENT_JVMARGS -Xbootclasspath/p:/Users/bstiles/bin/hsqldb.jar -jar "${HSQLDB_JAR_PATH}" --rcFile "$AUTH_FILE" "$@"

