#!/bin/bash

function usage {
    echo "usage: $(basename "$0") [-d output_dir] file [file...]"
    exit 1
}

output_dir=.

if [ -n "$1" -a "$1" = "-d" ]; then
    shift
    if [ $# -eq 0 ]; then
        usage
    elif [ -d "$1" ]; then
        output_dir="$1"
        shift
    else
        echo "$1 does not exist!"
        usage
    fi
fi

if [ $# -eq 0 ]; then
    usage
fi

# 20090624 bstiles: convert 6.5.1 dithers differently than 6.4.1 and 
# produces inferior results.
echo "!! Using older 'convert'."

for x in "$@"; do
    name="$(basename "${x%.pdf}")"
    if [ -n "$(file "$x" | grep "PDF document")" ]; then
        /usr/local/bin/convert +dither -density 204x196 -compress Group4 -monochrome "$x" "${output_dir}/${name}.tiff"
        echo "Converted $x to TIFF"
    else
        echo "!! $x is not a PDF"
    fi
done
