#!/bin/bash
. "$(dirname "$0")"/init.sh

SOURCE="/Volumes/AMP Documents/Dad/"
DEST="rsync://5.26.66.191/work"
BACKUP_DIR=backup

rsync \
--backup \
--backup-dir=$BACKUP_DIR \
--checksum \
--exclude=.DS_Store \
--exclude=$BACKUP_DIR \
--archive \
--copy-links \
--compress \
--partial \
--progress \
--stats \
--human-readable \
--log-file=/tmp/sync-dad.log \
"$SOURCE" \
"$DEST"
#--delete \
