#!/bin/bash
shopt -s extglob

function abort {
    if [ -n "$1" ]; then
        echo "$1"
    fi
    exit 1
}

here="$(cd "$(dirname "$0")";pwd)"

rsync \
--include=\*.java \
--recursive \
--progress \
--stats \
--human-readable \
--log-file=/tmp/sync-java-scripts.log \
"/Users/bstiles/Development/Projects/RE/Sling Scripts/src/apps/" \
"/Volumes/localhost/apps/"
if [ $? -ne 0 ]; then
    /usr/local/bin/growlnotify -m "!! FAILED !!"
else
    /usr/local/bin/growlnotify -m synced
fi
