#!/bin/bash
shopt -s extglob
set -o errexit

here=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

function abort {
    [ $# -gt 0 ] && echo "$*"
    exit 1
}

function display_help {
cat <<EOF
usage: $(basename "$0") pom-dir
  pom-dir     Directory containing the project POM for which to determine
              a classpath.
EOF
}

function abort_and_display_help {
    display_help && echo
    abort "$@"
}

[[ "$1" = @(--help|-h) ]] && display_help && exit 0
[ -z "$1" ] && abort_and_display_help "pom-dir not specified!"
[ ! -f "$1"/pom.xml ] && abort_and_display_help "pom-dir does not contain a POM.xml: $1!"
dir="$1"

set -o nounset

cp="$(find "$dir/target" -type f -name \*.jar -print0 | xargs -0 echo | tr ' ' ':')"
echo "$cp:$(mvn -o dependency:build-classpath -f "$dir/pom.xml" | grep '^/.*')"
