#!/usr/bin/env bash
[ $BASH_VERSINFO -gt 3 ] || { echo "Bash 4+ is required."; exit 1; }

set -o errexit -o pipefail -o nounset
shopt -s extglob nullglob
unset CDPATH

declare -ir ERR_GENERAL=1
declare -ir ERR_BAD_CMD_LINE=113
declare -ir ERR_PRECONDITION_VIOLATED=112
declare -ir ERR_MAX_LINK_DEPTH_EXCEEDED=111
declare -ir ERR_CMD_NOT_FOUND=110
declare -ir ERR_NON_EXISTENT_DIR=109
# Use 64-100 for other exit codes.

declare -r here=$(cd -- "${BASH_SOURCE[0]%/*}" && pwd)

display_help() {
cat <<EOF
usage: ${0##*/} [opts] input-file

   --generate-only  Generate only. Don't open.
-w|--watch          Watch and rerun on file change.
-h|--help           Displays usage information.

Run PlantUML, outputting to SVG (set type=XXX to change output format).
EOF
}
require() {
    eval [[ \$\{${1:?require was called without arguments!}-\} ]] \
         '||' abort \$ERR_BAD_CMD_LINE \$\{2-\$1 is required!\} \$\{*:3\}
}
abort() {
    local -i err_code=${1:?abort called without err_code}
    (( err_code == ERR_BAD_CMD_LINE )) && {
        display_help; echo; echo "-- ABORTED:"
    }
    shift; (( $# > 0 )) && echo "$*" >&2
    exit $err_code
}

watch() {
    file=${1-}
    require file
    fswatch --latency 0.11 \
            --one-per-batch "$1" \
        | xargs -n1 "$0" "$1"
}

main() {
    while (( $# > 0 )); do
        case $1 in
            -w|--watch)
                watching=true
                ;;
            --generate-only)
                generate_only=true
                ;;
            *)
                break
        esac
        shift
    done

    : ${type:=svg}

    if [[ ${watching-} == true ]]; then
        while [[ ${1-} ]]; do
            watch "$1"&
            shift
        done
        wait
    else
        dir=$(mktemp -d)
        # java -version
        #      -XX:+UseEpsilonGC \
        #      -XX:+AlwaysPreTouch \
        time java -Djava.awt.headless=true \
             -XX:+UnlockExperimentalVMOptions \
             -Xms512m \
             -Xmx512m \
             -jar ~/Config/emacs-config/lisp/org-extensions/plantuml.jar \
             -t$type \
             -verbose \
             -o "$dir" \
             "$1"
        ls $dir
        mv "$dir"/* "$(dirname "$1")"
        rmdir "$dir"
        if [[ ! ${generate_only-} ]]; then
            open -ga Safari "${1//.*}"{,_*}.$type
        fi
    fi
}

# Handle help
[[ $# < 1 || ${1-} == @(--help|-h) ]] && { display_help; exit 0; }
main "$@"
