#!/usr/bin/env bash
set -o errexit -o pipefail -o nounset
shopt -s extglob
unset CDPATH

declare -ir ERR_GENERAL=1
declare -ir ERR_BAD_CMD_LINE=113
declare -ir ERR_PRECONDITION_VIOLATED=112
declare -ir ERR_MAX_LINK_DEPTH_EXCEEDED=111
declare -ir ERR_CMD_NOT_FOUND=110
declare -ir ERR_NON_EXISTENT_DIR=109
declare -ir ERR_NON_EXISTENT_PROFILE=108
# Use 64-108 for other exit codes.

declare -r here=$(cd -- "${BASH_SOURCE[0]%/*}" && pwd)

display_help() {
cat <<EOF
usage: ${0##*/} [profile]
usage: ${0##*/} [opts] [profile]

-c|--command     Run commands piped into stdin.
-l|--list        List profiles.
-h|--help        Displays usage information.

Change to ~/SmartKable and set up environment. 'profile' selects a
project-specific environment. (May be empty.)
EOF
}
require() {
    eval [[ \$\{${1:?require was called without arguments!}-\} ]] \
         '||' abort \$ERR_BAD_CMD_LINE \$\{2-\$1 is required!\} \$\{*:3\}
}
abort() {
    local -i err_code=${1:?abort called without err_code}
    (( err_code == ERR_BAD_CMD_LINE )) && {
        display_help; echo; echo "-- ABORTED:"
    }
    shift; (( $# > 0 )) && echo "$*" >&2
    exit $err_code
}

main() {
    local cmd profile

    while (( $# > 0 )); do
        case $1 in
            -l|--list)
                {
                    ls -1 ~/SmartKable/Config/sk-*.env | sed -E 's/.*sk-(.*).env/\1/'
                } 2> /dev/null \
                    || echo 'No profiles.'
                exit
                ;;
            -c|--command)
                cmd=true
                ;;
            *)
                profile=$1
                break
        esac
        shift
    done

    [[ ! ${profile-} || -f ~/SmartKable/Config/sk-$profile.env ]] \
        || abort $ERR_NON_EXISTENT_PROFILE "Profile doesn't exist."

    if [[ ${cmd-} ]]; then
        {
            # 2019-06-05 bstiles: Turn off profile inclusion in
            # .bashrc as if this were an interactive shell.
            echo __no_profile=true
            cat ~/SmartKable/Config/sk${profile:+-$profile}.env
            cat
        } | exec bash
    else
        exec bash --init-file ~/SmartKable/Config/sk${1:+-$1}.env
    fi
}

# Handle help
[[ ${1-} == @(--help|-h) ]] && { display_help; exit 0; }
main "$@"
