#!/usr/bin/env bash
[ $BASH_VERSINFO -gt 3 ] || { echo "Bash 4+ is required."; exit 1; }

set -o errexit -o pipefail -o nounset
shopt -s extglob nullglob
unset CDPATH

declare -ir ERR_GENERAL=1
declare -ir ERR_BAD_CMD_LINE=113
declare -ir ERR_PRECONDITION_VIOLATED=112
declare -ir ERR_MAX_LINK_DEPTH_EXCEEDED=111
declare -ir ERR_CMD_NOT_FOUND=110
declare -ir ERR_NON_EXISTENT_DIR=109
# Use 64-100 for other exit codes.

declare -r here=$(cd -- "${BASH_SOURCE[0]%/*}" && pwd)

display_help() {
cat <<EOF
usage: ${0##*/} [command]

-h|--help        Displays usage information.

Run a command in a SmartKable environment. Same as running \`sk\` to
enter a SmartKable environment and then running \`sk ...\` to run a
command.
EOF
}
require() {
    eval [[ \$\{${1:?require was called without arguments!}-\} ]] \
         '||' abort \$ERR_BAD_CMD_LINE \$\{2-\$1 is required!\} \$\{*:3\}
}
abort() {
    local -i err_code=${1:?abort called without err_code}
    (( err_code == ERR_BAD_CMD_LINE )) && {
        display_help; echo; echo "-- ABORTED:"
    }
    shift; (( $# > 0 )) && echo "$*" >&2
    exit $err_code
}

main() {
    local profile
    if [[ ${1-} == @(-p|--profile) ]]; then
        profile=$2
        shift 2
    fi
    {
        local x
        [[ ${INSIDE_EMACS-} ]] && echo export GIT_PAGER=
        printf sk
        for x in "$@"; do
            printf ' "%s"' "$x"
        done
        echo
        echo exit
    } | exec "$here"/sk --command ${profile:-}
}

 # Handle help
[[ $# < 1 || ${1-} == @(--help|-h) ]] && { display_help; exit 0; }
main "$@"
