#!/usr/bin/env bash

# [[ 1 == $(ls -1d /Library/Java/JavaVirtualMachines/graalvm* | wc | awk '{print $1;}') ]] \
#     || {
#     echo "Looks like graal has been updated. Update ~/bin/on-the-path/with-graalvm"
#     exit 1
# }

version=graalvm-ce-java11-22.0.0.2

export JAVA_HOME=/Library/Java/JavaVirtualMachines/$version/Contents/Home
export GRAALVM_HOME=$JAVA_HOME
export PATH=/Library/Java/JavaVirtualMachines/$version/Contents/Home/bin:"$PATH"

exec "$@"
