#!/bin/bash
shopt -s extglob
set -o errexit
set -o nounset
unset CDPATH

ERR_GENERAL=1
ERR_BAD_CMD_LINE=113
ERR_PRECONDITION_VIOLATED=112
ERR_MAX_LINK_DEPTH_EXCEEDED=111
ERR_CMD_NOT_FOUND=110
ERR_NON_EXISTENT_DIR=109
ERR_PROFILE_NOT_FOUND=64
# Use 64-108 for other exit codes.

here=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)

function display_help {
cat <<EOF
usage: $(basename "$0") profile cmd [args]

-h|--help        Displays usage information.

Run CMD with AWS_ACCESS_KEY_ID and AWS_SERCRET_ACCESS_KEY set in the
environment for the specified PROFILE.
EOF
}

function abort {
    local err_code
    err_code=${1:?abort called without err_code}
    [[ $err_code = $ERR_BAD_CMD_LINE ]] && {
        display_help; echo; echo "-- ABORTED:"
    }
    shift; [[ $# -gt 0 ]] && echo "$*"
    exit $err_code
}

# Handle help
[[ ${1-} = @(--help|-h) ]] && display_help && exit 0

# Require argument
[[ $# -lt 2 ]] && abort $ERR_BAD_CMD_LINE "PROFILE and CMD are required."

profile=$1
shift

export AWS_ACCESS_KEY_ID=$(aws configure get aws_access_key_id --profile "$profile")
[[ -n ${AWS_ACCESS_KEY_ID:-} ]] || abort $ERR_PROFILE_NOT_FOUND
export AWS_SECRET_ACCESS_KEY=$(aws configure get aws_secret_access_key --profile "$profile")
[[ -n ${AWS_SECRET_ACCESS_KEY:-} ]] || abort $ERR_PROFILE_NOT_FOUND

exec "$@"
