#!/usr/bin/env bash

# [[ 1 == $(ls -1d /Library/Java/JavaVirtualMachines/graalvm* | wc | awk '{print $1;}') ]] \
#     || {
#     echo "Looks like graal has been updated. Update ~/bin/on-the-path/with-graalvm"
#     exit 1
# }

export JAVA_HOME=/Library/Java/JavaVirtualMachines/graalvm-ce-java11-19.3.0.2/Contents/Home
export PATH=/Library/Java/JavaVirtualMachines/graalvm-ce-java11-19.3.0.2/Contents/Home/bin:"$PATH"

exec "$@"
